package net.risesoft.common.sendms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IPlatformService", targetNamespace = "http://message.szjs.gov.cn")
public interface IPlatformService {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getReplySms", targetNamespace = "http://message.szjs.gov.cn", className = "cn.gov.szjs.message.GetReplySms")
	@ResponseWrapper(localName = "getReplySmsResponse", targetNamespace = "http://message.szjs.gov.cn", className = "cn.gov.szjs.message.GetReplySmsResponse")
	public String getReplySms(@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param sendDate
	 * @param sender
	 * @param smsContent
	 * @param productCode
	 * @param priority
	 * @param receiveMobile
	 * @param receiveName
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "sendSmsNeedReply", targetNamespace = "http://message.szjs.gov.cn", className = "cn.gov.szjs.message.SendSmsNeedReply")
	@ResponseWrapper(localName = "sendSmsNeedReplyResponse", targetNamespace = "http://message.szjs.gov.cn", className = "cn.gov.szjs.message.SendSmsNeedReplyResponse")
	public String sendSmsNeedReply(@WebParam(name = "productCode", targetNamespace = "") String productCode,
			@WebParam(name = "receiveMobile", targetNamespace = "") String receiveMobile,
			@WebParam(name = "receiveName", targetNamespace = "") String receiveName,
			@WebParam(name = "smsContent", targetNamespace = "") String smsContent,
			@WebParam(name = "sender", targetNamespace = "") String sender,
			@WebParam(name = "priority", targetNamespace = "") int priority,
			@WebParam(name = "sendDate", targetNamespace = "") String sendDate);

	/**
	 * 
	 * @param sendDate
	 * @param sender
	 * @param smsContent
	 * @param productCode
	 * @param priority
	 * @param receiveMobile
	 * @param receiveName
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "sendSms", targetNamespace = "http://message.szjs.gov.cn", className = "cn.gov.szjs.message.SendSms")
	@ResponseWrapper(localName = "sendSmsResponse", targetNamespace = "http://message.szjs.gov.cn", className = "cn.gov.szjs.message.SendSmsResponse")
	public String sendSms(@WebParam(name = "productCode", targetNamespace = "") String productCode,
			@WebParam(name = "receiveMobile", targetNamespace = "") String receiveMobile,
			@WebParam(name = "receiveName", targetNamespace = "") String receiveName,
			@WebParam(name = "smsContent", targetNamespace = "") String smsContent,
			@WebParam(name = "sender", targetNamespace = "") String sender,
			@WebParam(name = "priority", targetNamespace = "") int priority,
			@WebParam(name = "sendDate", targetNamespace = "") String sendDate);

}
