package net.risesoft.common.sendms;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * PlatformServiceService service = new PlatformServiceService();
 * IPlatformService portType = service.getPlatformServicePort();
 * portType.getReplySms(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "PlatformServiceService", targetNamespace = "http://message.szjs.gov.cn", wsdlLocation = "http://message.szjs.gov.cn:8001/construct-platform/service/SMSService?wsdl")
public class PlatformServiceService extends Service {

	private final static URL PLATFORMSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(PlatformServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = PlatformServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://message.szjs.gov.cn:8001/construct-platform/service/SMSService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://message.szjs.gov.cn:8001/construct-platform/service/SMSService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		PLATFORMSERVICESERVICE_WSDL_LOCATION = url;
	}

	public PlatformServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public PlatformServiceService() {
		super(PLATFORMSERVICESERVICE_WSDL_LOCATION, new QName("http://message.szjs.gov.cn", "PlatformServiceService"));
	}

	/**
	 * 
	 * @return returns IPlatformService
	 */
	@WebEndpoint(name = "PlatformServicePort")
	public IPlatformService getPlatformServicePort() {
		try{
			return super.getPort(new QName("http://message.szjs.gov.cn", "PlatformServicePort"), IPlatformService.class);
		}catch(Exception e){
			e.printStackTrace();
			return null;
		}
	}

}
